language: java

before_install:
  - sudo apt-get update -qq
  - sudo apt-git install texinfo dos2unix

script: ./.travis-build.sh

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

notifications:
  email:
    - mernst@cs.washington.edu
    - markro@cs.washington.edu
