language: java

script: travis_wait 120 ./.travis-build.sh

addons:
  apt:
    packages:
      - texinfo

sudo: false

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

notifications:
  email:
    - mernst@cs.washington.edu
    - markro@cs.washington.edu
