language: java

script: ./.travis-build.sh

addons:
  apt:
    packages:
    - texinfo
    - dos2unix

sudo: false

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

notifications:
  email:
    - mernst@cs.washington.edu
    - markro@cs.washington.edu
