sudo: false

language: generic

services:
  - docker

# jdkany contains extra packages that permit it to be used to build the manual
env:
  - OS=ubuntu JDKVER=jdk7 GROUP=quick-txt-diff
  - OS=ubuntu JDKVER=jdk7 GROUP=nonquick-txt-diff
  - OS=ubuntu JDKVER=jdk7 GROUP=non-txt-diff
  - OS=ubuntu JDKVER=jdk8 GROUP=quick-txt-diff
  - OS=ubuntu JDKVER=jdk8 GROUP=nonquick-txt-diff
  - OS=ubuntu JDKVER=jdk8 GROUP=non-txt-diff
  - OS=ubuntu JDKVER=jdkany GROUP=misc
## It's not trivial to install jdk7 on current fedora.
#  - OS=fedora JDKVER=jdk7 GROUP=quick-txt-diff
#  - OS=fedora JDKVER=jdk7 GROUP=nonquick-txt-diff
#  - OS=fedora JDKVER=jdk7 GROUP=non-txt-diff
  - OS=fedora JDKVER=jdk8 GROUP=quick-txt-diff
  - OS=fedora JDKVER=jdk8 GROUP=nonquick-txt-diff
  - OS=fedora JDKVER=jdk8 GROUP=non-txt-diff
  - OS=fedora JDKVER=jdkany GROUP=misc
  - OS=fedora23 JDKVER=jdk8 GROUP=nonquick-txt-diff

# Currently-failing jobs
matrix:
  allow_failures:
    - env: OS=fedora23 JDKVER=jdk8 GROUP=nonquick-txt-diff
    - env: OS=fedora23 JDKVER=jdk8 GROUP=nonquick-txt-diff

before_install:
  - npm install --save-dev travis-after-all

before_script:
- docker pull mdernst/$OS-for-daikon-$JDKVER > /dev/null

script:
- docker run mdernst/$OS-for-daikon-$JDKVER /bin/sh -c "export JAVA_HOME=\`which javac|xargs readlink -f|xargs dirname|xargs dirname\` && git clone --quiet --depth 3 https://github.com/codespecs/daikon.git daikon && cd daikon && java -version && javac -version && ./.travis-build.sh $GROUP"

after_script:
  - |
      declare exitCode;
      $(npm bin)/travis-after-all
      exitCode=$?

      if [ "$exitCode" -eq 0 ]; then
        if [[ ($TRAVIS_BRANCH == master) &&
              ($TRAVIS_PULL_REQUEST == false) ]] ; then
          curl -LO https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh
          sh trigger-travis.sh typetests daikon-typecheck $TRAVISTOKEN
        fi
      fi

git:
  depth: 3
